### ISSUE TITLE
AutoModelForMaskedLM无法成功load

### ISSUE THREAD

**Issue by Ht-zhang-xianyu** [JunnYu/GAU-alpha-pytorch#2]
哈喽，这边是从huggingface库过来的
看到好像无法用transformer的auto系列直接加载

`>>> from transformers import AutoModelForMaskedLM
>>>
>>> model = AutoModelForMaskedLM.from_pretrained("junnyu/chinese_GAU-alpha-char_L-24_H-768")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 423, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/anaconda3/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 725, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/anaconda3/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 432, in __getitem__
    raise KeyError(key)
KeyError: 'gau_alpha'`

不知道是不是我使用有问题 
还是模型中加了gau_alpha的问题 
如果是后者 不知道后续是否有更新修复的打算？

**Comment by JunnYu** [comment]
建议看一下本仓库的readme使用。
